### ISSUE TITLE
Problem: Sentry is not integrated on Truflation API

### ISSUE THREAD

**Issue by williamrusdyputra** [truflation/api-adapter#9]
We need to integrate Sentry here for monitoring

SENTRY_DSN=https://7857595d1f7615447e0f1fe1ac1dec88@o4507655688880128.ingest.us.sentry.io/4508047811018752

**Comment by georgeciubotaru** [comment]
@williamrusdyputra Can you please check why it fails: https://github.com/truflation/api-adapter/actions/runs/11141400108

**Comment by williamrusdyputra** [comment]
@georgeciubotaru 
https://github.com/truflation/api-adapter/pull/12

this PR will fix the dependency installation, please review if there is any missing step

**Comment by georgeciubotaru** [comment]
@williamrusdyputra Still fails

**Comment by williamrusdyputra** [comment]
@georgeciubotaru found out the problem is because I didn't realize the ApiAdapter is being used on `minertoken` and `nuon`, I will update the code

**Comment by williamrusdyputra** [comment]
I think its finally succeeded

**Comment by williamrusdyputra** [comment]
I will close this issue as its deployed
